package com.m_landalex.ufc.dbinitialization;

import java.time.LocalDate;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.google.common.collect.Lists;
import com.m_landalex.ufc.data.Address;
import com.m_landalex.ufc.data.Announcer;
import com.m_landalex.ufc.data.Country;
import com.m_landalex.ufc.data.Event;
import com.m_landalex.ufc.data.Fight;
import com.m_landalex.ufc.data.FightCard;
import com.m_landalex.ufc.data.Fighter;
import com.m_landalex.ufc.data.Location;
import com.m_landalex.ufc.data.MainCard;
import com.m_landalex.ufc.data.PreliminaryCard;
import com.m_landalex.ufc.data.Referee;
import com.m_landalex.ufc.data.Trainingteam;
import com.m_landalex.ufc.data.Ufc;
import com.m_landalex.ufc.data.UfcInterEmployee;
import com.m_landalex.ufc.data.WeightClass;
import com.m_landalex.ufc.service.UfcService;
import com.m_landalex.ufc.serviceXA.UfcServiceXA;

@Service
public class DBInitialization {

	@Autowired(required = false)
	private UfcService ufcService;
	@Autowired
	private UfcServiceXA ufcServiceXA;
	
	@PostConstruct
	public void setupInitialization() {
		
		Location location = Location.builder()
				.country(Country.UAE)
				.hallName("UFC Fight Island")
				.address(Address.builder()
						.city("Abu-Dhabi")
						.street("Yas Island")
						.houseNumber("No information")
						.postCode("No information")
						.build())
				.build();
		
		MainCard mainCard = MainCard.builder()
				.fights(Lists.newArrayList(
						Fight.builder()
							.fightNumberInCard(0)
							.referee(Referee.MARIO_YAMASAKI)
							.fighters(Lists.newArrayList(
									Fighter.builder()
										.weightClass(WeightClass.Lightweight)
										.ufcRanked(4)
										.firstName("Conor")
										.lastName("McGregor")
										.age(32)
										.trainingteam(Trainingteam.builder()
												.teamName("SBG IRELAND")
												.address(Address.builder()
														.city("Dublin")
														.street("Goldenbridge Industrial Estate")
														.houseNumber("Unit 13")
														.postCode("D08 WK22")
														.build())
												.build())
										.wins(22)
										.loses(4)
										.undecided(0)
										.build(),
									Fighter.builder()
										.weightClass(WeightClass.Lightweight)
										.ufcRanked(2)
										.firstName("Dustin")
										.lastName("Poirier")
										.age(31)
										.trainingteam(Trainingteam.builder()
												.teamName("AMERICAN TOP TEAM")
												.address(Address.builder()
														.city("Coconut Creek")
														.street("SR 7")
														.houseNumber("5750")
														.postCode("33073")
														.build())
												.build())
										.wins(26)
										.loses(6)
										.undecided(0)
										.build()))
							.build(),
						Fight.builder()
							.fightNumberInCard(0)
							.referee(Referee.DAN_MIRAGLIOTTA)
							.fighters(Lists.newArrayList(
									Fighter.builder()
										.weightClass(WeightClass.Lightweight)
										.ufcRanked(6)
										.firstName("Dan")
										.lastName("Hooker")
										.age(30)
										.trainingteam(Trainingteam.builder()
												.teamName("CITY KICKBOXING")
												.address(Address.builder()
														.city("Auckland")
														.street("Haultain Street")
														.houseNumber("10")
														.postCode("1010")
														.build())
												.build())
										.wins(20)
										.loses(9)
										.undecided(0)
										.build(),
									Fighter.builder()
										.weightClass(WeightClass.Lightweight)
										.ufcRanked(0)
										.firstName("Michael")
										.lastName("Chandler")
										.age(34)
										.trainingteam(Trainingteam.builder()
												.teamName("SANFORD MMA")
												.address(Address.builder()
														.city("Deerfield Beach")
														.street("Hillsboro Technology Dr")
														.houseNumber("366")
														.postCode("33441")
														.build())
												.build())
										.wins(21)
										.loses(5)
										.undecided(0)
										.build()))
							.build(),
							Fight.builder()
							.fightNumberInCard(0)
							.referee(Referee.MARC_GODDARD)
							.fighters(Lists.newArrayList(Fighter.builder()
										.weightClass(WeightClass.Flyweight)
										.ufcRanked(6)
										.firstName("Jessica")
										.lastName("Eye")
										.age(33)
										.trainingteam(Trainingteam.builder()
												.teamName("STRONG STYLE CLEVELAND")
												.address(Address.builder()
														.city("Independence")
														.street("Granger Rd")
														.houseNumber("6900")
														.postCode("44131")
														.build())
												.build())
										.wins(15)
										.loses(8)
										.undecided(0)
										.build(),
									Fighter.builder()
										.weightClass(WeightClass.Flyweight)
										.ufcRanked(7)
										.firstName("Joanna")
										.lastName("Calderwood")
										.age(34)
										.trainingteam(Trainingteam.builder()
												.teamName("DINKY NINJA FIGHT TEAM")
												.address(Address.builder()
														.city("No infomation")
														.street("No infomation")
														.houseNumber("No infomation")
														.postCode("No infomation")
														.build())
												.build())
										.wins(14)
										.loses(4)
										.undecided(0)
										.build()))
							.build(),
							Fight.builder()
							.fightNumberInCard(0)
							.referee(Referee.MIKE_BELTRAN)
							.fighters(Lists.newArrayList(Fighter.builder()
										.weightClass(WeightClass.Light_heavyweight)
										.ufcRanked(0)
										.firstName("Khalil")
										.lastName("Rountree Jr.")
										.age(30)
										.trainingteam(Trainingteam.builder()
												.teamName("SYNDICATE MMA - LAS VEGAS")
												.address(Address.builder()
														.city("Las Vegas")
														.street("Rainbow Blvd")
														.houseNumber("6315 S")
														.postCode("89118")
														.build())
												.build())
										.wins(9)
										.loses(4)
										.undecided(0)
										.build(),
									Fighter.builder()
										.weightClass(WeightClass.Light_heavyweight)
										.ufcRanked(0)
										.firstName("Marcin")
										.lastName("Prachnio")
										.age(32)
										.trainingteam(Trainingteam.builder()
												.teamName("No infomation")
												.address(Address.builder()
														.city("No infomation")
														.street("No infomation")
														.houseNumber("No infomation")
														.postCode("No infomation")
														.build())
												.build())
										.wins(13)
										.loses(5)
										.undecided(0)
										.build()))
							.build()))
				.build();
		
		PreliminaryCard preliminaryCard = PreliminaryCard.builder()
				.fights(Lists.newArrayList(
						Fight.builder()
						.fightNumberInCard(0)
						.referee(Referee.STEVE_MAZZAGATTI)
						.fighters(Lists.newArrayList(
								Fighter.builder()
									.weightClass(WeightClass.Flyweight)
									.ufcRanked(8)
									.firstName("Marina")
									.lastName("Rodriguez")
									.age(33)
									.trainingteam(Trainingteam.builder()
											.teamName("No infomation")
											.address(Address.builder()
													.city("No infomation")
													.street("No infomation")
													.houseNumber("No infomation")
													.postCode("No infomation")
													.build())
											.build())
									.wins(12)
									.loses(1)
									.undecided(2)
									.build(),
								Fighter.builder()
									.weightClass(WeightClass.Flyweight)
									.ufcRanked(9)
									.firstName("Amanda")
									.lastName("Ribas")
									.age(26)
									.trainingteam(Trainingteam.builder()
											.teamName("No infomation")
											.address(Address.builder()
													.city("No infomation")
													.street("No infomation")
													.houseNumber("No infomation")
													.postCode("No infomation")
													.build())
											.build())
									.wins(10)
									.loses(1)
									.undecided(0)
									.build()))
						.build(),
					Fight.builder()
						.fightNumberInCard(0)
						.referee(Referee.DAN_MIRAGLIOTTA)
						.fighters(Lists.newArrayList(
								Fighter.builder()
									.weightClass(WeightClass.Middleweight)
									.ufcRanked(14)
									.firstName("Brad")
									.lastName("Tavares")
									.age(32)
									.trainingteam(Trainingteam.builder()
											.teamName("No infomation")
											.address(Address.builder()
													.city("No infomation")
													.street("No infomation")
													.houseNumber("No infomation")
													.postCode("No infomation")
													.build())
											.build())
									.wins(17)
									.loses(7)
									.undecided(0)
									.build(),
								Fighter.builder()
									.weightClass(WeightClass.Middleweight)
									.ufcRanked(0)
									.firstName("Antonio")
									.lastName("Carlos Junior")
									.age(30)
									.trainingteam(Trainingteam.builder()
											.teamName("AMERICAN TOP TEAM")
											.address(Address.builder()
													.city("Coconut Creek")
													.street("SR 7")
													.houseNumber("5750")
													.postCode("33073")
													.build())
											.build())
									.wins(11)
									.loses(4)
									.undecided(0)
									.build()))
						.build(),
						Fight.builder()
						.fightNumberInCard(0)
						.referee(Referee.MARIO_YAMASAKI)
						.fighters(Lists.newArrayList(Fighter.builder()
									.weightClass(WeightClass.Lightweight)
									.ufcRanked(0)
									.firstName("Matt")
									.lastName("Frevola")
									.age(29)
									.trainingteam(Trainingteam.builder()
											.teamName("No information")
											.address(Address.builder()
													.city("No information")
													.street("No information")
													.houseNumber("No information")
													.postCode("No information")
													.build())
											.build())
									.wins(8)
									.loses(1)
									.undecided(1)
									.build(),
								Fighter.builder()
									.weightClass(WeightClass.Lightweight)
									.ufcRanked(0)
									.firstName("Ottman")
									.lastName("Azaitar")
									.age(30)
									.trainingteam(Trainingteam.builder()
											.teamName("No information")
											.address(Address.builder()
													.city("No information")
													.street("No information")
													.houseNumber("No information")
													.postCode("No information")
													.build())
											.build())
									.wins(13)
									.loses(0)
									.undecided(0)
									.build()))
						.build(),
						Fight.builder()
						.fightNumberInCard(0)
						.referee(Referee.MIKE_BELTRAN)
						.fighters(Lists.newArrayList(Fighter.builder()
									.weightClass(WeightClass.Middleweight)
									.ufcRanked(0)
									.firstName("Andrew")
									.lastName("Sanchez")
									.age(32)
									.trainingteam(Trainingteam.builder()
											.teamName("No information")
											.address(Address.builder()
													.city("No information")
													.street("No information")
													.houseNumber("No information")
													.postCode("No information")
													.build())
											.build())
									.wins(12)
									.loses(5)
									.undecided(0)
									.build(),
								Fighter.builder()
									.weightClass(WeightClass.Middleweight)
									.ufcRanked(0)
									.firstName("Andre")
									.lastName("Muniz")
									.age(30)
									.trainingteam(Trainingteam.builder()
											.teamName("No information")
											.address(Address.builder()
													.city("No information")
													.street("No information")
													.houseNumber("No information")
													.postCode("No information")
													.build())
											.build())
									.wins(20)
									.loses(4)
									.undecided(0)
									.build()))
						.build()))
				.build();
		
		FightCard fightCard = FightCard.builder()
				.mainCard(mainCard)
				.preliminaryCard(preliminaryCard)
				.build();
		
		Event event = Event.builder()
				.eventName("UFC")
				.eventNumber(257)
				.announcer(Announcer.BRUCE_BUFFER)
				.eventData(LocalDate.of(2021, 1, 24))
				.eventLocation(location)
				.fightCard(fightCard)
				.build();
		
		Ufc ufc = Ufc.builder()
				.ufcEvent(event)
				.ufcAddress(Address.builder()
						.city("Las Vegas")
						.street("Torrey Pines Dr")
						.houseNumber("6650 S")
						.postCode("89118")
						.build())
				.ufcInterEmployee(UfcInterEmployee.builder()
						.position("President")
						.firstName("Dana")
						.lastName("White")
						.age(51)
						.address(Address.builder()
								.city("Las Vegas")
								.street("West Sahara Ave")
								.houseNumber("2960")
								.postCode("89102")
								.build())
						.build())
				.build();
		
		ufcServiceXA.save(ufc);
		
	}
	
}
